import React from 'react'
import Categories from './Categories'

export const metadata = {
  title: "Categories - Inquiry Bazaar",
  description: "Generated by create next app",
};

export default async function page() {
  return (
    <Categories />
  )
}
