import React from 'react'
import Industries from './Industries'

export const metadata = {
  title: "Industries - Promote Bharat",
  description: "Generated by create next app",
};

export default async function page() {
    return (
        <Industries />
    )
}
